name: zup_landing
publish_to: "none"

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.7.0
  flutter_svg: ^2.0.10+1
  routefly: ^2.0.4
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+2
  zup_ui_kit:
    git:
      url: "https://github.com/Zup-Protocol/zup-ui-kit.git"
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.7.0

flutter_gen:
  output: lib/gen/
  line_length: 200
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  fonts:
    - family: "SF Pro Rounded"
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf
          weight: 100
